# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78fd882fd4280ce545c7a78b5552e86126efc53d915341e93ef6b05256b150e85655496222f807ffb01a70854c8b02ff7a6633e897918e46ef3c853b85cc6bce

test:
  secret_key_base: 1b7eff001ed3810c01161cc7f692a2c735fa0f99166d0ea47171fcce1f6c6390020d35f113900e1c7a28460eceb10650684b00c194702aca5cd896dc77ac8a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
